"""Initial migration

Revision ID: 16b0fa4f4d09
Revises: b9d8dc0c1fbd
Create Date: 2024-08-11 07:50:28.527736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16b0fa4f4d09'
down_revision: Union[str, None] = 'b9d8dc0c1fbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
