"""Add career survey tables

Revision ID: 1d0f37b042cd
Revises: 4d37185033ad
Create Date: 2024-08-07 05:16:10.363728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d0f37b042cd'
down_revision: Union[str, None] = '4d37185033ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.String(), nullable=False),
    sa.Column('choice_a', sa.String(), nullable=True),
    sa.Column('choice_b', sa.String(), nullable=True),
    sa.Column('choice_c', sa.String(), nullable=True),
    sa.Column('choice_d', sa.String(), nullable=True),
    sa.Column('next_question_a_id', sa.Integer(), nullable=True),
    sa.Column('next_question_b_id', sa.Integer(), nullable=True),
    sa.Column('next_question_c_id', sa.Integer(), nullable=True),
    sa.Column('next_question_d_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['next_question_a_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['next_question_b_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['next_question_c_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['next_question_d_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_id'), 'questions', ['id'], unique=False)
    op.create_table('responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.UUID(as_uuid=True), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('answer', sa.String(), nullable=True),
    sa.Column('free_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_responses_id'), 'responses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_responses_id'), table_name='responses')
    op.drop_table('responses')
    op.drop_index(op.f('ix_questions_id'), table_name='questions')
    op.drop_table('questions')
    # ### end Alembic commands ###
