"""ts: String => Float

Revision ID: 2cfbdc9b98f7
Revises: 7752e1a45a76
Create Date: 2024-08-06 03:59:44.322657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cfbdc9b98f7'
down_revision: Union[str, None] = '7752e1a45a76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Use explicit cast for PostgreSQL
    op.execute(
        "ALTER TABLE daily_report ALTER COLUMN ts TYPE FLOAT USING ts::FLOAT;"
    )
    op.execute(
        "ALTER TABLE times_tweet ALTER COLUMN ts TYPE FLOAT USING ts::FLOAT;"
    )
    op.execute(
        "ALTER TABLE times_tweet ALTER COLUMN thread_ts TYPE FLOAT USING thread_ts::FLOAT;"
    )


def downgrade() -> None:
    # Revert changes with explicit cast
    op.execute(
        "ALTER TABLE times_tweet ALTER COLUMN thread_ts TYPE VARCHAR USING thread_ts::VARCHAR;"
    )
    op.execute(
        "ALTER TABLE times_tweet ALTER COLUMN ts TYPE VARCHAR USING ts::VARCHAR;"
    )
    op.execute(
        "ALTER TABLE daily_report ALTER COLUMN ts TYPE VARCHAR USING ts::VARCHAR;"
    )



# 以下おそらく不要で削除OKになります meme 0806

# """ts: String => Float

# Revision ID: 2cfbdc9b98f7
# Revises: 7752e1a45a76
# Create Date: 2024-08-06 03:59:44.322657

# """
# from typing import Sequence, Union

# from alembic import op
# import sqlalchemy as sa


# # revision identifiers, used by Alembic.
# revision: str = '2cfbdc9b98f7'
# down_revision: Union[str, None] = '7752e1a45a76'
# branch_labels: Union[str, Sequence[str], None] = None
# depends_on: Union[str, Sequence[str], None] = None


# def upgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.alter_column('daily_report', 'ts',
#                existing_type=sa.VARCHAR(),
#                type_=sa.Float(),
#                existing_nullable=False)
#     op.alter_column('times_tweet', 'ts',
#                existing_type=sa.VARCHAR(),
#                type_=sa.Float(),
#                existing_nullable=False)
#     op.alter_column('times_tweet', 'thread_ts',
#                existing_type=sa.VARCHAR(),
#                type_=sa.Float(),
#                existing_nullable=True)
#     # ### end Alembic commands ###


# def downgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.alter_column('times_tweet', 'thread_ts',
#                existing_type=sa.Float(),
#                type_=sa.VARCHAR(),
#                existing_nullable=True)
#     op.alter_column('times_tweet', 'ts',
#                existing_type=sa.Float(),
#                type_=sa.VARCHAR(),
#                existing_nullable=False)
#     op.alter_column('daily_report', 'ts',
#                existing_type=sa.Float(),
#                type_=sa.VARCHAR(),
#                existing_nullable=False)
#     # ### end Alembic commands ###
