"""Initial migration

Revision ID: 2f1e7f880f1e
Revises: 8c55fa3a7143
Create Date: 2024-08-13 00:35:42.009245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f1e7f880f1e'
down_revision: Union[str, None] = '8c55fa3a7143'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
