"""daily_report, times_tweet : add => created_at

Revision ID: 4d37185033ad
Revises: 2cfbdc9b98f7
Create Date: 2024-08-06 07:02:40.966349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d37185033ad'
down_revision: Union[str, None] = '2cfbdc9b98f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_report', sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.add_column('times_tweet', sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('times_tweet', 'created_at')
    op.drop_column('daily_report', 'created_at')
    # ### end Alembic commands ###
