"""Initial migration, models=employee,slack_user_info,daily_report

Revision ID: 4dfb2c2b6bef
Revises: 
Create Date: 2024-08-05 05:14:11.872512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dfb2c2b6bef'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slack_user_info',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('real_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('times_tweet',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_report',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('ts', sa.String(), nullable=False),
    sa.Column('edited', sa.String(), nullable=True),
    sa.Column('edited_by', sa.String(length=100), nullable=True),
    sa.Column('edited_ts', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['slack_user_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('project', sa.String(length=100), nullable=False),
    sa.Column('slack_user_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['slack_user_id'], ['slack_user_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee')
    op.drop_table('daily_report')
    op.drop_table('times_tweet')
    op.drop_table('slack_user_info')
    # ### end Alembic commands ###
