"""Initial migration

Revision ID: 76a2e43a6c5f
Revises: 0b9254e1e313
Create Date: 2024-08-12 08:02:49.573997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76a2e43a6c5f'
down_revision: Union[str, None] = '0b9254e1e313'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
