"""Rename Channel to TimesList

Revision ID: 7752e1a45a76
Revises: 290d33765dc4
Create Date: 2024-08-05 13:04:33.846765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7752e1a45a76'
down_revision: Union[str, None] = '290d33765dc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_report', 'edited')
    op.drop_column('daily_report', 'edited_ts')
    op.drop_column('daily_report', 'edited_by')
    op.drop_column('times_tweet', 'edited')
    op.drop_column('times_tweet', 'edited_ts')
    op.drop_column('times_tweet', 'edited_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('times_tweet', sa.Column('edited_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('times_tweet', sa.Column('edited_ts', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('times_tweet', sa.Column('edited', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('daily_report', sa.Column('edited_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('daily_report', sa.Column('edited_ts', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('daily_report', sa.Column('edited', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
