"""Initial migration

Revision ID: 7774e15bb0cc
Revises: f4c26eab9b46
Create Date: 2024-08-12 12:06:47.924806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7774e15bb0cc'
down_revision: Union[str, None] = 'f4c26eab9b46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
