"""Initial migration

Revision ID: 80a4f1ae55d9
Revises: bd0e0435f51b
Create Date: 2024-08-11 12:36:41.544358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80a4f1ae55d9'
down_revision: Union[str, None] = 'bd0e0435f51b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
