"""Initial migration

Revision ID: 92cf0940fe55
Revises: c1e2ee3ec411
Create Date: 2024-08-10 08:15:01.182728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92cf0940fe55'
down_revision: Union[str, None] = 'c1e2ee3ec411'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
