"""Initial migration

Revision ID: af4eaaecf4dc
Revises: fdf7b1ada1af
Create Date: 2024-08-13 04:52:51.550898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af4eaaecf4dc'
down_revision: Union[str, None] = 'fdf7b1ada1af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
