"""updated times_tweet table and created times_list table

Revision ID: be32a12d8404
Revises: 4dfb2c2b6bef
Create Date: 2024-08-05 05:56:52.672315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be32a12d8404'
down_revision: Union[str, None] = '4dfb2c2b6bef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('times_list',
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('channel_name', sa.String(length=100), nullable=False),
    sa.Column('channel_id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['slack_user_info.id'], ),
    sa.PrimaryKeyConstraint('channel_id')
    )
    op.add_column('times_tweet', sa.Column('channel_id', sa.String(), nullable=False))
    op.add_column('times_tweet', sa.Column('user_id', sa.String(length=100), nullable=False))
    op.add_column('times_tweet', sa.Column('text', sa.Text(), nullable=False))
    op.add_column('times_tweet', sa.Column('ts', sa.String(), nullable=False))
    op.add_column('times_tweet', sa.Column('thread_ts', sa.String(), nullable=True))
    op.add_column('times_tweet', sa.Column('parent_user_id', sa.String(), nullable=True))
    op.add_column('times_tweet', sa.Column('edited', sa.String(), nullable=True))
    op.add_column('times_tweet', sa.Column('edited_by', sa.String(length=100), nullable=True))
    op.add_column('times_tweet', sa.Column('edited_ts', sa.String(), nullable=True))
    op.create_foreign_key(None, 'times_tweet', 'times_list', ['channel_id'], ['channel_id'])
    op.create_foreign_key(None, 'times_tweet', 'slack_user_info', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'times_tweet', type_='foreignkey')
    op.drop_constraint(None, 'times_tweet', type_='foreignkey')
    op.drop_column('times_tweet', 'edited_ts')
    op.drop_column('times_tweet', 'edited_by')
    op.drop_column('times_tweet', 'edited')
    op.drop_column('times_tweet', 'parent_user_id')
    op.drop_column('times_tweet', 'thread_ts')
    op.drop_column('times_tweet', 'ts')
    op.drop_column('times_tweet', 'text')
    op.drop_column('times_tweet', 'user_id')
    op.drop_column('times_tweet', 'channel_id')
    op.drop_table('times_list')
    # ### end Alembic commands ###
