"""1st migration, models=employee,slack_user_info,daily_report, times_tweet, times_list

Revision ID: e7839dcae4f3
Revises: 7752e1a45a76
Create Date: 2024-08-06 07:04:39.314123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7839dcae4f3'
down_revision: Union[str, None] = '7752e1a45a76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
