"""Initial migration, 0805: 8tables create

Revision ID: ebceee4ad05a
Revises: d5dd83112890
Create Date: 2024-08-08 12:57:29.012234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebceee4ad05a'
down_revision: Union[str, None] = 'd5dd83112890'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
