"""Initial migration, 0805: 8tables create

Revision ID: f28445cb5c9f
Revises: 522040829833
Create Date: 2024-08-09 02:29:43.557280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f28445cb5c9f'
down_revision: Union[str, None] = '522040829833'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # employeeテーブルのslack_user_idカラムに一意制約を追加
    op.create_unique_constraint('uq_employee_slack_user_id', 'employee', ['slack_user_id'])
    op.add_column('responses', sa.Column('slack_user_id', sa.String(), nullable=False))
    op.drop_constraint('responses_employee_id_fkey', 'responses', type_='foreignkey')
    op.create_foreign_key(None, 'responses', 'employee', ['slack_user_id'], ['slack_user_id'])
    op.drop_column('responses', 'employee_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 一意制約を削除
    op.drop_constraint('uq_employee_slack_user_id', 'employee', type_='unique')
    op.add_column('responses', sa.Column('employee_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'responses', type_='foreignkey')
    op.create_foreign_key('responses_employee_id_fkey', 'responses', 'employee', ['employee_id'], ['id'])
    op.drop_column('responses', 'slack_user_id')
    # ### end Alembic commands ###
